---
version: 1.0.0
slug: mlflow
name: MLflow
description: MLflow tracking server for managing machine learning experiments, models, and artifacts
url: https://github.com/WickM/mlflow-hassio-addon
arch:
  - aarch64
  - amd64
image: homeassistant/{arch}-addon-mlflow
init: false
options:
  port: 5000
  storage_path: /mlflow
  backend_store_uri: sqlite:///mlflow.db
  default_artifact_root: /mlflow/artifacts
  host: 0.0.0.0
  workers: 4
schema:
  port: int
  storage_path: str
  backend_store_uri: str
  default_artifact_root: str
  host: str
  workers: int
ports:
  5000/tcp: 5000
startup: services
watchdog: tcp://[HOST]:5000
map:
  - mlflow:rw
