name: MLflow
version: latest
slug: mlflow
description: MLflow tracking server for managing machine learning experiments, models, and artifacts
url: https://github.com/WickM/mlflow-hassio-addon
webui: "[PROTO:ssl]://[HOST]:[PORT:5000]"
arch:
  - aarch64
  - amd64
init: false
startup: services
map:
  - share
  - ssl
backup: cold
backup_exclude:
  - "**/logs"
  - "**/artifacts"
schema:
  TZ: str?
  port: int
  storage_path: str
  backend_store_uri: str
  default_artifact_root: str
  workers: int
  git_enabled: bool
options:
  TZ: Etc/UTC
  port: 5000
  storage_path: /mlflow
  backend_store_uri: sqlite:///mlflow/mlflow.db
  default_artifact_root: /mlflow/artifacts
  workers: 4
  git_enabled: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: MLflow Web UI
image: ghcr.io/wickm/mlflow-hassio-addon
